### ISSUE TITLE
Exercise: Tic-Tac-Toe

### ISSUE THREAD

**Issue by hqtan** [hqtan/react-katas#1]
## Exercise: implement Tic Tac Toe

see details of exercise [here](https://gitlog.pub/rounds?r=tic-tac-toe)

## Task Breakdown
- [x] setup dev environment : make changes easy, to make easy changes
  - [x] set up linting with `eslint` (see [this commit](https://github.com/hqtan/react-katas/commit/557339f2917908234647767628fc932060e2256a))
  - [x] set up Jest testing framework (already done as part of CRA install)
- [x] make a clickable square that logs a message to console (see #2 )
- [x] update square to display 'X' on click, and update state (see #3 )
- [x] generate board made of 3x3 squares (see #4)
- [x] draw state change diagram for one player (see #5)
- [x] add `row`, `column`, `filled`(boolean) state to square (see #6)
- [x] add player state. Should have name (hardcode 'X' or 'O' ??), and list of squares player has clicked (see #7 )
- [x] add logic to determine if player has won (see #13)
  - [x] player has 3 squares in same row (see #10)
  - [x] player has 3 squares in same column (see #11)
  - [x] player has 3 squares in same diagonal (see #12)
- [x] add logic to choose player's turn (see #14)
- [x] add logic to determine a draw (see #16)
